apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mysql
          image: mysql:8
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name: MYSQL_DATABASE
            value: app
          - name: MYSQL_USER
            value: app
          - name: MYSQL_PASSWORD
            value: supersecret
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: persistent-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
     - metadata:
         name: persistent-storage
       spec:
         accessModes: [ "ReadWriteOnce" ]
         storageClassName: "local-path"
         resources:
          requests: 
           storage: 1Gi
